version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm install --legacy-peer-deps

  build:
    commands:
      - echo "Building React Vite project..."
      - npm run build

  post_build:
    commands:
      - echo "Deploying to S3 bucket..."
      - aws s3 sync dist/ s3://affilliate-frontend --delete

artifacts:
  base-directory: dist
  files:
    - '**/*'
