export const GET_ALL_BRANDS = "GET_ALL_BRANDS";
export const CREATE_BRAND = "CREATE_BRAND";
export const UPDATE_BRAND = "UPDATE_BRAND";
export const DELETE_BRAND = "DELETE_BRAND";


// Error Messages
export const ERROR_FETCHING_ALL_BRANDS = "ERROR_FETCHING_ALL_BRANDS";
export const ERROR_FETCHING_CREATE_BRAND = "ERROR_FETCHING_CREATE_BRAND";
export const ERROR_FETCHING_UPDATE_BRAND = "ERROR_FETCHING_UPDATE_BRAND";
export const ERROR_FETCHING_DELETE_BRAND = "ERROR_FETCHING_DELETE_BRAND";