export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";


// Error Messages
export const ERROR_FETCHING_ALL_CATEGORIES = "ERROR_FETCHING_ALL_CATEGORIES";
export const ERROR_FETCHING_CREATE_CATEGORY = "ERROR_FETCHING_CREATE_CATEGORY";
export const ERROR_FETCHING_UPDATE_CATEGORY = "ERROR_FETCHING_UPDATE_CATEGORY";
export const ERROR_FETCHING_DELETE_CATEGORY = "ERROR_FETCHING_DELETE_CATEGORY";