export const GET_ALL_PAYMENTS = "GET_ALL_PAYMENTS";
export const UPDATE_VERIFY_STATUS = "UPDATE_VERIFY_STATUS";
export const UPDATE_PAYMENT_STATUS = "UPDATE_PAYMENT_STATUS";
export const CHECK_STATUS = "CHECK_STATUS";
export const SUBMIT_PROOF = "SUBMIT_PROOF";