// Action Types
export const GET_ALL_PRODUCTS = "products/fetchAll";
export const GET_PRODUCT_BY_ID = "products/fetchById";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "products/delete";

export const PRODUCT_DETAILS="PRODUCT_DETAILS"
export const ALL_PRODUCTS_BY_CATEGORY="ALL_PRODUCTS_BY_CATEGORY"
export const ALL_PRODUCTS_BY_BRAND="ALL_PRODUCTS_BY_BRAND"
export const ALL_PRODUCTS_BY_SUBCATEGORY="ALL_PRODUCTS_BY_SUBCATEGORY"
export const SEARCH_PRODUCTS="SEARCH_PRODUCTS"

// Error Messages
export const ERROR_FETCHING_ALL_PRODUCTS = "Error fetching products";
export const ERROR_FETCHING_PRODUCT_DETAILS = "ERROR_FETCHING_PRODUCT_DETAILS";
export const ERROR_FETCHING_ALL_PRODUCTS_BY_BRAND = "ERROR_FETCHING_ALL_PRODUCTS_BY_BRAND";
export const ERROR_FETCHING_ALL_PRODUCTS_BY_CATEGORY = "ERROR_FETCHING_ALL_PRODUCTS_BY_CATEGORY";
export const ERROR_FETCHING_ALL_PRODUCTS_BY_SUBCATEGORY = "ERROR_FETCHING_ALL_PRODUCTS_BY_SUBCATEGORY";
export const ERROR_FETCHING_DELETE_PRODUCT = "ERROR_FETCHING_DELETE_PRODUCT";
export const ERROR_FETCHING_CREATE_PRODUCT = "ERROR_FETCHING_CREATE_PRODUCT";
export const ERROR_FETCHING_UPDATE_PRODUCT = "ERROR_FETCHING_UPDATE_PRODUCT";
export const ERROR_FETCHING_SEARCH_PRODUCTS = "ERROR_FETCHING_SEARCH_PRODUCTS";

