
export const CREATE_REVIEW = "CREATE_REVIEW";
export const CREATE_ADMIN_REVIEW = "CREATE_ADMIN_REVIEW";
export const UPLOAD_ADMIN_REVIEW_IMG= "UPLOAD_ADMIN_REVIEW_IMG";
export const GET_ALL_REVIEWS = "GET_ALL_REVIEWS";



export const ERROR_FETCHING_CREATE_REVIEW = "ERROR_FETCHING_CREATE_REVIEW";
export const ERROR_FETCHING_CREATE_ADMIN_REVIEW = "ERROR_FETCHING_CREATE_ADMIN_REVIEW";
export const ERROR_FETCHING_UPLOAD_ADMIN_REVIEW_IMG = "ERROR_FETCHING_UPLOAD_ADMIN_REVIEW_IMG";
export const ERROR_FETCHING_GET_ALL_REVIEWS = "ERROR_FETCHING_GET_ALL_REVIEWS";