export const LOGIN_USER = "LOGIN_USER";
export const USER_PROFILE = "USER_PROFILE";
export const LOAD_USER = "LOAD_USER";
export const ALL_USERS = "ALL_USERS";
export const LOGOUT_USER = "LOGOUT_USER";
export const DELETE_USER = "DELETE_USER";
export const UPDATE_USER_ROLE = "UPDATE_USER_ROLE";
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";


// Error Messages
export const ERROR_FETCHING_LOGIN_USER = "ERROR_FETCHING_LOGIN_USER";
export const ERROR_FETCHING_USER_PROFILE = "ERROR_FETCHING_USER_PROFILE";
export const ERROR_FETCHING_LOAD_USER = "ERROR_FETCHING_LOAD_USER";
export const ERROR_FETCHING_ALL_USERS = "ERROR_FETCHING_ALL_USERS";
export const ERROR_FETCHING_LOGOUT_USER = "ERROR_FETCHING_LOGOUT_USER";
export const ERROR_FETCHING_DELETE_USER = "ERROR_FETCHING_DELETE_USER";
export const ERROR_FETCHING_UPDATE_USER_ROLE = "ERROR_FETCHING_UPDATE_USER_ROLE";
export const ERROR_FETCHING_UPDATE_USER_PROFILE = "ERROR_FETCHING_UPDATE_USER_PROFILE";
export const ERROR_FETCHING_CHANGE_PASSWORD = "ERROR_FETCHING_CHANGE_PASSWORD";